### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by xiabingbao-ok** [modelscope/AdaSeq#12]
### What is your question?

如何推理？

### What have you tried?

训练模型之后自动就有了pred.txt，请问这个文件是在哪里生成的？

### What's your environment?

- AdaSeq Version (e.g., 1.0 or master):
- ModelScope Version (e.g., 1.0 or master):
- PyTorch Version (e.g., 1.12.1):
- OS (e.g., Ubuntu 20.04):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by izhx** [comment]
感谢提问。单纯的推理功能正在开发，预计半个月到一个月，目前有 [test](https://github.com/modelscope/AdaSeq/blob/master/adaseq/commands/test.py) 功能。

这个文件是 [`ner_dumpper`](https://github.com/modelscope/AdaSeq/blob/master/adaseq/data/dataset_dumpers/named_entity_recognition_dataset_dumper.py) 保存的，它就是一个在评测调用的特殊的 `metric`。

**Comment by xiabingbao-ok** [comment]
谢谢您的回答！！！不过在我训练脚本完成后，模型保存的文件是best_model.pth，请问修改哪里可以将模型的保存结果保存为modelscope的中模型格式（含有这些：config.json  configuration.json  pytorch_model.bin  README.md  resources  vocab.txt）

**Comment by huangshenno1** [comment]
> 谢谢您的回答！！！不过在我训练脚本完成后，模型保存的文件是best_model.pth，请问修改哪里可以将模型的保存结果保存为modelscope的中模型格式（含有这些：config.json configuration.json pytorch_model.bin README.md resources vocab.txt）

`AdaSeq >= 0.6.0`刚刚支持这个功能，无须任何修改，训练完成后会生成`output`或`output_best`目录，这个目录和modelscope模型格式相同。
详见https://github.com/modelscope/AdaSeq/blob/master/docs/tutorials/model_inference_zh.md

**Comment by BGDSW** [comment]
我在使用这个推理的时候，遇到了ValueError: unknown url type: 'adaseq-0.6.6-py3-none-any.whl.metadata'
请问这个是怎么回事呢

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline(Tasks.named_entity_recognition, '/data3/huyan/liheng/tmp/AdaSeq/AdaSeq/experiments/eBay/231125005305.028950/output_best')
result = p('Nike Reax TR Mesh Herren Sneaker low Turnschuhe Sportschuhe Freizeitschuhe')

print(result)


报错如下
2023-11-25 22:15:49,690 - modelscope - INFO - PyTorch version 2.1.1+cu118 Found.
2023-11-25 22:15:49,691 - modelscope - INFO - Loading ast index from /home/huyan/liheng/.cache/modelscope/ast_indexer
2023-11-25 22:15:49,788 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 c652a785900e4613e32639cfe65e325f and a total number of 945 components indexed
Traceback (most recent call last):
  File "/data3/huyan/liheng/tmp/AdaSeq/AdaSeq/test.py", line 4, in <module>
    p = pipeline(Tasks.named_entity_recognition, '/data3/huyan/liheng/tmp/AdaSeq/AdaSeq/experiments/eBay/231125005305.028950/output_best')
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 135, in pipeline
    register_plugins_repo(cfg.safe_get('plugins'))
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/site-packages/modelscope/utils/plugins.py", line 446, in register_plugins_repo
    module_name, module_version, _ = get_modules_from_package(plugin)
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/site-packages/modelscope/utils/plugins.py", line 736, in get_modules_from_package
    data = get(package, tmpdir=tmpdir)
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/site-packages/modelscope/utils/plugins.py", line 688, in get
    target, _headers = _download_dist(url, scratch_file, index_url,
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/site-packages/modelscope/utils/plugins.py", line 549, in _download_dist
    target, _headers = urlretrieve(url, scratch_file, auth=auth)
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/site-packages/modelscope/utils/plugins.py", line 504, in urlretrieve
    res = opener.open(url, data=data)
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/urllib/request.py", line 501, in open
    req = Request(fullurl, data)
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/data3/huyan/liheng/conda/envs/pytorch_d/lib/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'adaseq-0.6.6-py3-none-any.whl.metadata'

但实际上我已经成功安装了 adaseq == 0.6.6

**Comment by breadbread1984** [comment]
可以清空/data3/huyan/liheng/tmp/AdaSeq/AdaSeq/experiments/eBay/231125005305.028950/output_best/configuration.json最底下plugin的list中的内容，变成空list。但是运行可能还有其他问题。
