### ISSUE TITLE
[Feature] 建议将pytorch版本升级到2.0

### ISSUE THREAD

**Issue by fmdallas** [modelscope/AdaSeq#20]
### Is your feature request related to a problem?

我的电脑是nvidia - rtx 3060版本，cuda版本是12.1， torch版本是2.0，目前这个Adaseq的torch版本是1.12.1，cuda是10.2，感觉太不方便了。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmdallas** [comment]
/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/torch/cuda/__init__.py:146: UserWarning:
NVIDIA GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3060 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "/usr/local/pydev/AdaSeq/scripts/experiments/resume/230424163653.145389/output_best/test.py", line 6, in <module>
    result = p('1984年出生，中国国籍，汉族，硕士学历')
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 212, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 247, in _process_single
    out = self.forward(out, **forward_params)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/adaseq/pipelines/base.py", line 47, in forward
    return {**self.model(**inputs, **forward_params), **inputs}
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/adaseq/models/base.py", line 53, in __call__
    return self.postprocess(super()._call_impl(*args, **kwargs))
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/adaseq/models/sequence_labeling_model.py", line 110, in forward
    logits = self._forward(tokens)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/adaseq/models/sequence_labeling_model.py", line 143, in _forward
    x = self.embedder(**tokens)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/adaseq/modules/embedders/transformer_embedder.py", line 170, in forward
    encoded = self.encode(input_ids, attention_mask, token_type_ids)  # type: ignore
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/adaseq/modules/embedders/transformer_embedder.py", line 221, in encode
    parameters = {'input_ids': input_ids, 'attention_mask': attention_mask.float()}
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by huangshenno1** [comment]
@fmdallas 您好，torch版本不影响使用的，建议您根据自己环境的CUDA版本安装对应的pytorch，不一定要是1.12.1。

**Comment by fmdallas** [comment]
已经弄好了，安装了cuda116版本。谢谢！
