### ISSUE TITLE
cannot run the examples/bert_crf/resume.yaml under modelscope==1.1.2

### ISSUE THREAD

**Issue by TTCoding** [modelscope/AdaSeq#3]
### What is your question?

cannot run the examples/bert_crf/resume.yaml under modelscope==1.1.2

### What's your environment?

- AdaSeq Version (e.g., 1.0 or master):
- ModelScope Version (e.g., 1.0 or master):
- PyTorch Version (e.g., 1.12.1):
- OS (e.g., Ubuntu 20.04):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TTCoding** [comment]
Traceback (most recent call last):
  File "scripts/train.py", line 54, in <module>
    main(args)
  File "scripts/train.py", line 20, in main
    trainer = build_trainer(args)
  File "scripts/train.py", line 41, in build_trainer
    trainer = ms_build_trainer(trainer_name, kwargs)
  File "/home/pai/lib/python3.6/site-packages/modelscope/trainers/builder.py", line 20, in build_trainer
    return build_from_cfg(cfg, TRAINERS, default_args=default_args)
  File "/home/pai/lib/python3.6/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: NERTrainer: 'NERTrainer' object has no attribute 'cfg_modify_fn'

**Comment by izhx** [comment]
We have updated.
