### ISSUE TITLE
FileNotFoundError of try

### ISSUE THREAD

**Issue by CCengin** [modelscope/AdaSeq#31]
### What is your question?

when I run :"python scripts/train.py -c examples/bert_crf/configs/resume.yaml". 
it warns me: "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/XXX/.cache/huggingface/datasets/named_entity_recognition_dataset_builder/default-ef6495d2da4494b4/0.0.0/db737b9bb893f20fb03d04403a30bf7c033256c212b7e9f0ebc6e9c958535c51.incomplete/named_entity_recognition_dataset_builder-test-00000-00000-of-NNNNN.arrow'".

### Code (if necessary)

(base) PS C:\Users\XXX\Desktop\Graphic\AdaSeq> python scripts/train.py -c examples/bert_crf/configs/resume.yaml
2023-09-13 19:25:22,907 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-09-13 19:25:22,912 - modelscope - INFO - Loading ast index from C:\Users\XXX\.cache\modelscope\ast_indexer
2023-09-13 19:25:23,304 - modelscope - INFO - Loading done! Current index file version is 1.9.0, with md5 f8489c2bf624f5caf45aa5b79ca58350 and a total number of 921 components indexed       
2023-09-13 19:25:27,292 - modelscope - WARNING - The reference has been Deprecated in modelscope v1.4.0+, please use `from modelscope.msdatasets.dataset_cls.custom_datasets import TorchCustomDataset`
2023-09-13 19:25:27,356 - INFO - adaseq.data.dataset_manager - Will use a custom loading script: D:\conda\Lib\site-packages\adaseq\data\dataset_builders\named_entity_recognition_dataset_builder.py
Downloading and preparing dataset named_entity_recognition_dataset_builder/default to C:/Users/XXX/.cache/huggingface/datasets/named_entity_recognition_dataset_builder/default-ef6495d2da4494b4/0.0.0/db737b9bb893f20fb03d04403a30bf7c033256c212b7e9f0ebc6e9c958535c51...
Traceback (most recent call last):
  File "D:\conda\Lib\site-packages\datasets\builder.py", line 1618, in _prepare_split_single   
    writer = writer_class(
             ^^^^^^^^^^^^^
  File "D:\conda\Lib\site-packages\datasets\arrow_writer.py", line 334, in __init__
    self.stream = self._fs.open(fs_token_paths[2][0], "wb")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\conda\Lib\site-packages\fsspec\spec.py", line 1151, in open
    f = self._open(
        ^^^^^^^^^^^
  File "D:\conda\Lib\site-packages\fsspec\implementations\local.py", line 183, in _open        
    return LocalFileOpener(path, mode, fs=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\conda\Lib\site-packages\fsspec\implementations\local.py", line 285, in __init__     
    self._open()
  File "D:\conda\Lib\site-packages\fsspec\implementations\local.py", line 290, in _open        
    self.f = open(self.path, mode=self.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/XXX/.cache/huggingface/datasets/named_entity_recognition_dataset_builder/default-ef6495d2da4494b4/0.0.0/db737b9bb893f20fb03d04403a30bf7c033256c212b7e9f0ebc6e9c958535c51.incomplete/named_entity_recognition_dataset_builder-test-00000-00000-of-NNNNN.arrow'

### What's your environment?

- AdaSeq Version (e.g., 1.0 or master):
- ModelScope Version (e.g., 1.0 or master):
- PyTorch Version (e.g., 1.12.1):
- OS (e.g., Ubuntu 20.04):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhaonx** [comment]
same error

**Comment by houyuchao** [comment]
求助求助，相同的问题

**Comment by mxx910** [comment]
pip install ModelScope==1.9.5
this works for me
