### ISSUE TITLE
can not run ./examples/ICASSP2023_MUG_track4/end2end.sh under modelscope==1.1.2, 1.1.1 or 1.0.4

### ISSUE THREAD

**Issue by haiahaiah** [modelscope/AdaSeq#7]
### Checklist before your report.

- [X] I have verified that the issue exists against the `master` branch of AdaSeq.
- [X] I have read the relevant section in the [contribution guide](https://github.com/modelscope/adaseq/blob/master/CONTRIBUTING.md) on reporting bugs.
- [X] I have checked the [issues list](https://github.com/modelscope/adaseq/issues) for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/modelscope/adaseq/pulls) for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/modelscope/adaseq/commits/master) to find out if the bug was already fixed in the master branch.

### What happened?

AttributeError: 'ConfigDict' object has no attribute 'safe_get'

### Python traceback

start training....
2023-01-05 16:53:32,579 - modelscope - INFO - PyTorch version 1.12.1 Found.
2023-01-05 16:53:32,581 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-01-05 16:53:32,953 - modelscope - INFO - Loading done! Current index file version is 1.1.0, with md5 7c254489cd639574f9416078442cc193
Traceback (most recent call last):
  File "scripts/train.py", line 51, in <module>
    main(args)
  File "scripts/train.py", line 25, in main
    checkpoint_path=args.checkpoint_path,
  File "/mnt/workspace/workgroup/yuhai/kpe/adaseq/adaseq/commands/train.py", line 106, in train_model
    config.safe_get('experiment.exp_dir', 'experiments/'),
  File "/mnt/workspace/workgroup/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/config.py", line 296, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/mnt/workspace/workgroup/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/config.py", line 55, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'safe_get'

### Operating system

Ubuntu 18.04.5 LTS

### Python version

3.8.15

### Output of pip freeze

<details>
<summary><b>show/hide</b></summary>
<p>

```

```

</p>
</details>

### How to reproduce

bash ./examples/ICASSP2023_MUG_track4/end2end.sh ${sdk_token}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by izhx** [comment]
`safe_get` is added in modelscope 1.1.2, [commit bb5512](https://github.com/modelscope/modelscope/commit/bb5512d1ab938befc305ac6f3a0405eb062cef6f).

Maybe modelscope is not updated successfully?

**Comment by izhx** [comment]
应该只是简单的版本问题，可以加钉钉群一起看一下：4170025534

**Comment by haiahaiah** [comment]
I installed modelscope by `pip install "modelscope[nlp]==1.1.2" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`, the same error still exists.

**Comment by haiahaiah** [comment]
Sorry to bother you guys, I run the script by different environment whose modescope is not 1.1.2.
